
name: Code quality checks

on: [push]

env:
  NODE_VERSION: lts/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm ci
      working-directory: ./
      run: |
        npm ci
    - name: lint
      working-directory: ./
      run: |
        npm run lint
    - name: code style check
      working-directory: ./
      run: |
        npm run format
    
